### ISSUE TITLE
English fix

### ISSUE THREAD

**Issue by bagder** [KubikPixel/pipeinstall#4]
Original:

`A list of projects there use shell script pipe and cURL or Wget to instll it self.`

Proposed alternative:

`A list of projects that use a shell pipe and cURL or Wget to install themselves`

**Comment by KubikPixel** [comment]
Thanks is fixed.
BTW: engl. is not my native lang.

**Comment by bagder** [comment]
The top line of the web site still shows the former version.
